# Site settings
title: "TITLE"
email: "EMAIL" 
description: "DESCRIPTION" #> # this means to ignore newlines until "baseurl:"
baseurl: "BASEURL" # the subpath of your site, e.g. /blog/
url: "URL" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
